routes/admin.php
<?php

Route::namespace('Admin')->group(function () {
    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::resource('teacher', 'TeacherController')->except(['show']);
    Route::get('supervisor/index', 'TeacherController@supervisor_index');
    Route::resource('student', 'StudentController')->except(['show']);
    Route::resource('assign', 'AssignController')->except(['show']);
    Route::resource('research', 'ResearchController')->except(['show']);
    Route::resource('group', 'GroupController')->except(['show']);
    Route::resource('semester', 'SemesterController')->except(['show']);
    Route::resource('notice_category', 'NoticeCategoryController')->except(['show']);
    Route::get('notice_category/delete/{id}', 'NoticeCategoryController@delete');
    Route::resource('notice', 'NoticeController')->except(['show']);
    Route::get('setting', 'AdminController@setting')->name('setting');
    Route::post('save_group', 'GroupController@save_interest_group');
    Route::get('choice_list','InterestController@choice_list')->name('choice_list');
    Route::get('choice','InterestController@choice');
});

routes/web.php
<?php


Route::get('admin', function () {
    return redirect('admin/login');
});

Route::get('teacher', function () {
    return redirect('teacher/login');
});

Route::get('student', function () {
    return redirect('student/login');
});
Route::get('/admin', function () {
    return redirect('admin/login');
});

Route::namespace('Front')->group(function(){
    Route::get('/','HomeController@index');
    Route::get('/research-work','ResearchController@index');
    Route::get('/previous-research-work','ResearchController@previous');

});

Route::group(['prefix' => 'admin'], function () {

    Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Admin\Auth\LoginController@login');
    Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('logout');

    Route::get('/register', 'Admin\Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Admin\Auth\RegisterController@register');

    Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'student'], function () {
    Route::get('/login', 'Student\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Student\Auth\LoginController@login');
    Route::post('/logout', 'Student\Auth\LoginController@logout')->name('logout');

    Route::get('/register', 'Student\Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Student\Auth\RegisterController@register');

    Route::post('/password/email', 'Student\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'Student\Auth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'Student\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'Student\Auth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'teacher'], function () {
    Route::get('/login', 'Teacher\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Teacher\Auth\LoginController@login');
    Route::post('/logout', 'Teacher\Auth\LoginController@logout')->name('logout');

    Route::get('/register', 'Teacher\Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Teacher\Auth\RegisterController@register');

    Route::post('/password/email', 'Teacher\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'Teacher\Auth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'Teacher\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'Teacher\Auth\ResetPasswordController@showResetForm');
});

resources/views/admin/dashboard.blade.php
@extends('layout.admin.admin') @section('title','Dashboard') @section('content')
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Dashboard</h2>
    </div>
</div>
<div class="row">
    @if(Session::has('success'))
    <p class="alert alert-success message">{{ Session::get('success') }}</p>
    @endif @if(Session::has('error'))
    <p class="alert alert-warning message">{{ Session::get('error') }}</p>
    @endif
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-users fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ $total_teacher }}</div>
                        <div>Total Teacher</div>
                    </div>
                </div>
            </div>
            <a href="{{  route('admin.teacher.index') }}">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-users fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ $total_student }}</div>
                        <div>Total Registered User</div>
                    </div>
                </div>
            </div>
            <a href="{{  route('admin.student.index') }}">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>


    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-list fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ $total_research }}</div>
                        <div>Total Research Work</div>
                    </div>
                </div>
            </div>
            <a href="{{  route('admin.research.index') }}">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>


    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-bullhorn fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ $total_notice }}</div>
                        <div>Total Notice</div>
                    </div>
                </div>
            </div>
            <a href="{{  route('admin.notice.index') }}">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>







</div>

<br>

</div>

@endsection

resources/views/admin/setting.blade.php
@extends('layout.admin.admin') @section('title','Setting') @section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Setting</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Setting</a></li>

                        <li class="breadcrumb-item active">Setting</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <div class="content">

        <div class="row">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-body">
                        <form role="form" action="{{ route('admin.setting') }}" method="post" enctype="multipart/form-data">
                            @method('POST') @csrf
                            <div class="form-group">
                                <label for="exampleInputEmail1">Contact</label>
                                <input type="text" name="contact" value="{{ $setting->contact }}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Address</label>
                                <input type="text" name="address" value="{{ $setting->address }}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email</label>
                                <input type="text" name="email" value="{{ $setting->email }}" class="form-control">
                            </div>
                    </div>

                </div>
            </div>

            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Facebook</label>
                            <input type="text" name="facebook" value="{{ $setting->facebook }}" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Twitter</label>
                            <input type="text" name="twitter" value="{{ $setting->twitter }}" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Pinterest</label>
                            <input type="text" name="pinterest" value="{{ $setting->pinterest }}" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Instragram</label>
                            <input type="text" name="instagram" value="{{ $setting->instagram }}" class="form-control">
                        </div>

                    </div>

                </div>
            </div>

            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Update</button>


            </div>
            </form>

        </div>


    </div>

</div>
@push('extra-scripts')
<!-- <script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>

<script>
    CKEDITOR.replace('description');
</script> -->
@endpush @endsection