routes/admin.php
<?php

Route::namespace('Admin')->group(function () {
    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::resource('teacher', 'TeacherController')->except(['show']);
    Route::get('supervisor/index', 'TeacherController@supervisor_index');
    Route::resource('student', 'StudentController')->except(['show']);
    Route::resource('assign', 'AssignController')->except(['show']);
    Route::resource('research', 'ResearchController')->except(['show']);
    Route::resource('group', 'GroupController')->except(['show']);
    Route::resource('semester', 'SemesterController')->except(['show']);
    Route::resource('notice_category', 'NoticeCategoryController')->except(['show']);
    Route::get('notice_category/delete/{id}', 'NoticeCategoryController@delete');
    Route::resource('notice', 'NoticeController')->except(['show']);
    Route::get('setting', 'AdminController@setting')->name('setting');
    Route::post('save_group', 'GroupController@save_interest_group');
    Route::get('choice_list','InterestController@choice_list')->name('choice_list');
    Route::get('choice','InterestController@choice');
});

routes/web.php
<?php


Route::get('admin', function () {
    return redirect('admin/login');
});

Route::get('teacher', function () {
    return redirect('teacher/login');
});

Route::get('student', function () {
    return redirect('student/login');
});
Route::get('/admin', function () {
    return redirect('admin/login');
});

Route::namespace('Front')->group(function(){
    Route::get('/','HomeController@index');
    Route::get('/research-work','ResearchController@index');
    Route::get('/previous-research-work','ResearchController@previous');

});

Route::group(['prefix' => 'admin'], function () {

    Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Admin\Auth\LoginController@login');
    Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('logout');

    Route::get('/register', 'Admin\Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Admin\Auth\RegisterController@register');

    Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'student'], function () {
    Route::get('/login', 'Student\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Student\Auth\LoginController@login');
    Route::post('/logout', 'Student\Auth\LoginController@logout')->name('logout');

    Route::get('/register', 'Student\Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Student\Auth\RegisterController@register');

    Route::post('/password/email', 'Student\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'Student\Auth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'Student\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'Student\Auth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'teacher'], function () {
    Route::get('/login', 'Teacher\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Teacher\Auth\LoginController@login');
    Route::post('/logout', 'Teacher\Auth\LoginController@logout')->name('logout');

    Route::get('/register', 'Teacher\Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Teacher\Auth\RegisterController@register');

    Route::post('/password/email', 'Teacher\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'Teacher\Auth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'Teacher\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'Teacher\Auth\ResetPasswordController@showResetForm');
});

resources/views/layouts/admin/lib/header.blade.php
<header class="header">
    <div class="page-brand">
        <a class="link" href="{{ route('admin.dashboard') }}">
            <span class="brand">Admin
                <span class="brand-tip">PANEL</span>
            </span>
            <span class="brand-mini">AP</span>
        </a>
    </div>
    <div class="flexbox flex-1">
        <!-- START TOP-LEFT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li>
                <a class="nav-link sidebar-toggler js-sidebar-toggler"><i class="ti-menu"></i></a>
            </li>

        </ul>
        <!-- END TOP-LEFT TOOLBAR-->
        <!-- START TOP-RIGHT TOOLBAR-->
        <ul class="nav navbar-toolbar">


            <li class="dropdown dropdown-user">
                <a class="nav-link dropdown-toggle link" data-toggle="dropdown">
                    <img src="{{ asset('assets/back/img/admin-avatar.png')}}" />
                    <span></span>Admin<i class="fa fa-angle-down m-l-5"></i></a>
                <ul class="dropdown-menu dropdown-menu-right">

                    <li class="dropdown-divider"></li>
                    <!-- <a class="dropdown-item" href="login.html"><i class="fa fa-power-off"></i>Logout</a> -->

                    <a class="dropdown-item" title href="{{ url('/admin/logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                        <i class="fa fa-power-off"></i>Logout
                    </a>

                    <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>

                </ul>
            </li>
        </ul>
        <!-- END TOP-RIGHT TOOLBAR-->
    </div>
</header>

resources/views/layouts/admin/lib/sidebar.blade.php
<nav class="page-sidebar" id="sidebar">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div>
                <img src="{{ asset('assets/back/img/admin-avatar.png')}}" width="45px" />
            </div>
            <div class="admin-info">
                <div class="font-strong">Administrator</div>
                <small>Administrator</small>
            </div>
        </div>
        <ul class="side-menu metismenu">
            <li>
                <a class="active" href="{{ route('admin.dashboard') }}"><i class="sidebar-item-icon fa fa-th-large"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
            </li>
            <li class="heading">FEATURES</li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-users"></i>
                    <span class="nav-label">Teacher</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('admin.teacher.index') }}">Teacher</a>
                        <a href="{{ route('admin.teacher.create') }}">Add Teacher</a>
                    </li>

                </ul>
            </li>

        </ul>
    </div>
</nav>