routes/admin.php
<?php

Route::namespace('Admin')->group(function () {
    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::resource('teacher', 'TeacherController')->except(['show']);
    Route::get('supervisor/index', 'TeacherController@supervisor_index');
    Route::resource('student', 'StudentController')->except(['show']);
    Route::resource('assign', 'AssignController')->except(['show']);
    Route::resource('research', 'ResearchController')->except(['show']);
    Route::resource('group', 'GroupController')->except(['show']);
    Route::resource('semester', 'SemesterController')->except(['show']);
    Route::resource('notice_category', 'NoticeCategoryController')->except(['show']);
    Route::get('notice_category/delete/{id}', 'NoticeCategoryController@delete');
    Route::resource('notice', 'NoticeController')->except(['show']);
    Route::get('setting', 'AdminController@setting')->name('setting');
    Route::post('save_group', 'GroupController@save_interest_group');
    Route::get('choice_list','InterestController@choice_list')->name('choice_list');
    Route::get('choice','InterestController@choice');
});

routes/web.php
<?php


Route::get('admin', function () {
    return redirect('admin/login');
});

Route::get('teacher', function () {
    return redirect('teacher/login');
});

Route::get('student', function () {
    return redirect('student/login');
});
Route::get('/admin', function () {
    return redirect('admin/login');
});

Route::namespace('Front')->group(function(){
    Route::get('/','HomeController@index');
    Route::get('/research-work','ResearchController@index');
    Route::get('/previous-research-work','ResearchController@previous');

});

Route::group(['prefix' => 'admin'], function () {

    Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Admin\Auth\LoginController@login');
    Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('logout');

    Route::get('/register', 'Admin\Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Admin\Auth\RegisterController@register');

    Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'student'], function () {
    Route::get('/login', 'Student\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Student\Auth\LoginController@login');
    Route::post('/logout', 'Student\Auth\LoginController@logout')->name('logout');

    Route::get('/register', 'Student\Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Student\Auth\RegisterController@register');

    Route::post('/password/email', 'Student\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'Student\Auth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'Student\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'Student\Auth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'teacher'], function () {
    Route::get('/login', 'Teacher\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Teacher\Auth\LoginController@login');
    Route::post('/logout', 'Teacher\Auth\LoginController@logout')->name('logout');

    Route::get('/register', 'Teacher\Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Teacher\Auth\RegisterController@register');

    Route::post('/password/email', 'Teacher\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'Teacher\Auth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'Teacher\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'Teacher\Auth\ResetPasswordController@showResetForm');
});

app/Http/Controllers/Admin/ResearchController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Researchwork;
use App\Models\Student;
use App\Models\Teacher;
use Illuminate\Http\Request;
use Session;

class ResearchController extends Controller
{
    public function index()
    {
        $data =   [
            'researches' => Researchwork::with('teacher','group')->get()
        ];

        return view('admin.research.index')->with($data);
    }

    public function create()
    {
        $data =   [
            'teachers' => Teacher::orderBy('name')->get(),
            'students' => Student::orderBy('name')->get(),
        ];
        return view('admin.research.create')->with($data);
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $data['status']  = 1;

        if (Researchwork::create($data)) {
            Session::flash('success', 'Assign Added successfully!');
            return redirect(route('admin.research.index'));
        } else {
            Session::flash('error', 'Something Went wrong!');
            return redirect(route('admin.research.create'));
        }
    }

    public function edit(Assign $group)
    {
        $data =   [
            'group' => $group,
        ];

        return view('admin.research.edit')->with($data);
    }

    public function update(Request $request, Assign $group)
    {

        $group->group_id = $request->group_id;

        $group->updated_at = now();
        if ($group->update()) {
            Session::flash('success', 'Assign updated successfully');
            return redirect(route('admin.research.index'));
        } else {
            Session::flash('error', 'Failed to update vendor');
            return redirect(route('admin.research.index'));
        }
    }

    public function destroy(Assign $group)
    {
        if ($group->delete()) {
            Session::flash('success', 'Assign deleted successfully');
            return redirect(route('admin.research.index'));
        } else {
            Session::flash('success', 'Assign update failed');
            return redirect(route('admin.research.index'));
        }
    }

}

app/Http/Controllers/Front/ResearchController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Researchwork;
use Illuminate\Http\Request;

class ResearchController extends Controller
{
    public function index()
    {
        $data =   [
            'researches' => Researchwork::with('teacher','group')->where('status',2)->get()
        ];

        return view('front.research.index')->with($data);
    }


    public function previous()
    {
        $data =   [
            'researches' => Researchwork::with('teacher','group')->where('status',3)->get()
        ];

        return view('front.research.previous')->with($data);
    }




}

resources/views/admin/research/create.blade.php
@extends('layout.admin.admin') @section('title','Add Assign') @section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Add Assign</h2>
        </div>
    </div>

    <!-- Content Header (Page header) -->
    <section class="content-header">
        @if(Session::has('success'))
        <p class="alert alert-success" id="message">{{ Session::get('success') }}</p>
        @endif @if(Session::has('error'))
        <p class="alert alert-warning" id="message">{{ Session::get('error') }}</p>
        @endif

        <div class="container-fluid">
            <div class="row mb-1">
                <div class="col-sm-7">

                </div>
                <div class="col-sm-5">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}" style="color: #000 !important;">Home</a></li>
                        <li class="breadcrumb-item">Add Assign</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="col-md-8">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Add Assign</h3>
                </div>

                <form role="form" action="{{ route('admin.research.store') }}" method="post" enctype="multipart/form-data">
                    @method('POST') @csrf
                    <div class="card-body">

                         <div class="form-group">
                            <label for="exampleInputEmail1">Select Teacher</label>
                             <select name="teacher_id" class="form-control" id="">
                                 <option value="" disabled selected>Select</option>
                                 @foreach($teachers as $teacher)
                                    <option value="{{ $teacher->id }}">{{ $teacher->name }}</option>

                                 @endforeach
                             </select>
                        </div>
                         <div class="form-group">
                            <label for="exampleInputEmail1">Select Student</label>
                             <select name="student_id" class="form-control" id="">
                                 <option value="" disabled selected>Select</option>
                                 @foreach($students as $student)
                                    <option value="{{ $student->id }}">{{ $student->name }}</option>

                                 @endforeach
                             </select>
                        </div>



                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
            <!-- Form Element sizes --
        </div>
        <!-- /.card-body -->
        </div>
        <!-- /.card -->


        <!-- /.card -->

</div>
</section>
</div>
@endsection

resources/views/admin/research/edit.blade.php
@extends('layout.admin.admin') @section('title','Edit Assign') @section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Edit Assign</h2>
            </div>
        </div>

        <!-- Content Header (Page header) -->
        <section class="content-header">
            @if(Session::has('success'))
                <p class="alert alert-success" id="message">{{ Session::get('success') }}</p>
            @endif @if(Session::has('error'))
                <p class="alert alert-warning" id="message">{{ Session::get('error') }}</p>
            @endif

            <div class="container-fluid">
                <div class="row mb-1">
                    <div class="col-sm-7">

                    </div>
                    <div class="col-sm-5">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}" style="color: #000 !important;">Home</a></li>
                            <li class="breadcrumb-item">Edit Assign</li>
                        </ol>
                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="col-md-8">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Edit Assign</h3>
                    </div>

                    <form role="form" action="{{ route('admin.research.update',$research->id) }}" method="post" enctype="multipart/form-data">
                        @method('PUT') @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Enter name</label>
                                <input type="text" name="name" class="form-control" value="{{ $research->name }}" required>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Department</label>
                                <select name="department_id" class="form-control" id="">
                                    <option value="" >Select Department</option>
                                    @foreach($departments as $department)
                                        <option value="{{ $department->id }}" @if($research->department_id == $department->id) selected @endif>{{ $department->department_name }}</option>

                                    @endforeach
                                </select>
                            </div>


                            <div class="form-group">
                                <label for="exampleInputEmail1">Email</label>
                                <input type="text" name="email" class="form-control" value="{{ $research->email }}" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Password</label>
                                <input type="password" name="password" class="form-control" >
                            </div>


                            <div class="form-group">
                                <label for="exampleInputEmail1">Mobile</label>
                                <input type="text" name="mobile" class="form-control" value="{{ $research->mobile }}" required>
                            </div>


                            <div class="form-group">
                                <label for="exampleInputEmail1">Address</label>
                                <input type="text" name="address" class="form-control" value="{{ $research->address }}" required>
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
                <!-- Form Element sizes --
            </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->


            <!-- /.card -->

    </div>
    </section>
    </div>
@endsection

resources/views/admin/research/index.blade.php
@extends('layout.admin.admin') @section('title','Research Work') @section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Research Work</h2>
        </div>
    </div>

    <!-- Content Header (Page header) -->
    <section class="content-header">
        @if(Session::has('success'))
        <p class="alert alert-success" id="message">{{ Session::get('success') }}</p>
        @endif @if(Session::has('error'))
        <p class="alert alert-warning" id="message">{{ Session::get('error') }}</p>
        @endif

        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-7">

                </div>
                <div class="col-sm-5">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}" style="color: #000 !important;">Home</a></li>
                        <li class="breadcrumb-item">Research Work</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <section class="content">
                <div class="row">
                    <div class="col-12">

                        <div class="card">
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Topic Name</th>
                                            <th>Supvisor Name</th>
                                            <th>Group</th>
                                            <th>Added On</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($researches as $key=> $research)
                                        <tr>

                                            <td>{{ ++$key }}</td>
                                            <td>{{ $research->topic }}</td>
                                            <td>{{ $research->description }}</td>
                                            <td>{{ date('d-m-Y',strtotime($research->created_at)) }}</td>
                                            <td>

                                                <a href="{{ route('admin.research.edit',$research->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>

                                                <a class="" href="{{ route('admin.research.destroy',$research->id) }}" onclick="event.preventDefault();
                                document.getElementById('vendor-delete-form{{ $research->id }}').submit();">
                                                    <i class="fa fa-trash btn btn-danger btn-sm"></i>
                                                </a>
                                                <form id="vendor-delete-form{{ $research->id }}" action="{{ route('admin.research.destroy',$research->id) }}" method="post" style="display: none;">
                                                    {{ csrf_field() }} @method('DELETE')
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>

                                    </tfoot>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </section>

        </div>
    </section>
    <!-- /.content -->
</div>
@push('extra-css')
<link rel="stylesheet" href="{{asset('asset/back/vendor/datatables/css/dataTables.bootstrap4.css')}}"> @endpush @push('extra-scripts')
<script src="{{asset('asset/back/vendor/datatables/js/jquery.dataTables.js')}}"></script>
<script src="{{asset('asset/back/vendor/datatables/js/dataTables.bootstrap4.js')}}"></script>
<script>
    $(function() {
        $("#example1").DataTable();
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });
    });
</script>
@endpush @endsection